import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import {config} from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import AuthContext from "@/components/AuthContext";

config.autoAddCss = false


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {


    return (
        <html lang="en" className="h-[100vh] w-[100vw]">
        <body className="h-[100vh] w-[100vw] bg-black flex flex-col">
        <AuthContext>
            <NavBar></NavBar>
            {children}
        </AuthContext>
        </body>
        </html>
    );
}
