import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "../globals.css";
import NavBar from "@/components/NavBar";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import SideBarResponsive from "@/components/SideBarResponsive";
config.autoAddCss = false


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="w-full h-full flex md:flex-row flex-col-reverse gap-2" >
            <div className="flex justify-center items-center md:w-[10%] md:h-full w-full h-[60px] md:static z-10">
                <SideBarResponsive></SideBarResponsive>
            </div>
            {children}
        </div>
    );
}
